name: 'Create Release'
description: 'Create Release'
inputs:
  token:
    description: 'The token to use to access the GitHub API'
    required: true
  ref:
    description: 'Ref to create release with a tag'
    required: true
runs:
  using: 'node18'
  main: 'createRelease.js'