name: Release

on:
    push:
      tags:
        - 'v[0-9]+'

jobs:
    release:
        name: "Validate Code"
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: .
        steps:
            - uses: actions/checkout@v3
              with:
                fetch-depth: 0  

            - name: "Create Release"
              uses: ./.github/actions/createRelease
              with: 
                owner: ${{ github.repository_owner }}
                repo: ${{ github.event.repository.name }}
                token: ${{ secrets.GITHUB_TOKEN }}
                ref: ${{ github.event.ref }}
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}